export const THEMES = {
  Light: {
    "Bg": "background-color: #fef8f4;",
    "Card-bg": "background-color: #ffffff;",
    "Sidebar-bg": "background-color: #ffffff;",
    "Highlight-bg": "background-color: #ffe9dd;",
    "Tag-bg": "background-color: #ffe9dd;",
    "description-text": "color: rgba(77, 77, 77, 80);",
    "2nd-title-text": "color: rgba(77, 77, 77, 60);",
    "Title-text": "color: #1d3149;",
    "Alerts": "color: #1d3149;",
    "Success-tag": "color: #28a745;",
    "Success-tag-text": "color: #ffffff;",
    "users-stroke": "color: #fef8f4;",
    "users-bg": "background-color: #f2e7e0;",
    "users-text": "color: #ff6d18;",
    "Tag-text": "color: #1d3149;",
    "Pagination-bg": "background-color: #ffeee4;",
    "Active-Pagination-bg": "background-color: #1d3149;",
    "Active-Pagination-text": "color: #ffffff;",
    "Pagination-text": "color: #1d3149;",
    "Sidebar-active-text": "color: #1d3149;",
    "Sidebar-text": "color: #4d4d4d;",
    "Line": "color: #fff4ee;",
    "reply-card-bg": "background-color: #f7f8f9;",
    "choice-stroke": "color: rgba(77, 77, 77, 40);",
    "choosed-stroke": "color: #1d3149;",
  },
  Dark: {
    "Bg": "background-color: #292929;",
    "Card-bg": "background-color: #3c3c3c;",
    "Sidebar-bg": "background-color: #3c3c3c;",
    "Highlight-bg": "background-color: #ffceb2;",
    "Tag-bg": "background-color: #ffceb2;",
    "description-text": "color: rgba(255, 255, 255, 80);",
    "2nd-title-text": "color: rgba(255, 255, 255, 80);",
    "Title-text": "color: #fbfcfe;",
    "Alerts": "color: #fbfcfe;",
    "Success-tag": "color: #1e7b33;",
    "Success-tag-text": "color: #ffffff;",
    "users-stroke": "color: #282828;",
    "users-bg": "color: #ffceb2;",
    "users-text": "color: #3c3c3c;",
    "Tag-text": "color: #3c3c3c;",
    "Pagination-bg": "background-color: #3c3c3c;",
    "Active-Pagination-bg": "background-color: #ffceb2;",
    "Active-Pagination-text": "color: #3c3c3c;",
    "Pagination-text": "color: rgba(255, 255, 255, 80);",
    "Sidebar-active-text": "color: #3c3c3c;",
    "Sidebar-text": "color: #ffffff;",
    "Line": "color: rgba(255, 206, 178, 40);",
    "reply-card-bg": "background-color: #292929;",
    "choice-stroke": "color: #4d4d4d;",
    "choosed-stroke": "color: #292929;",
    },
  };
