import { Inter, Cairo, Lato } from "next/font/google";
import "./globals.css";
import Background from "../../components/LoginPages/Background/Background";
// import { ThemeProvider } from "@/context/ThemeContext";
import DarkModeToggle from "../../components/DarkModeToggle/DarkModeToggle";
import Head from "next/head";

// for multilanguage support
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import useLocale from "next-intl";

// const inter = Inter({ subsets: ["latin"] });
// const cairo = Cairo({ subsets: ["arabic", "latin-ext", "latin"], weight: ["400", "600", "800"] });
// const lato = Lato();

export const metadata = {
  title: "أكاديميا",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         {/* <ThemeProvider> */}
//         <div className="container">
//           {/* <DarkModeToggle /> */}
//           {children}
//         </div>
//         {/* </ThemeProvider> */}
//         <Background />
//       </body>
//     </html>
//   );
// }

export default async function LocaleLayout({ children, params: { locale } }) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  // const locale = useLocale();

  // {locale === 'ar' ? $('body').removeClass('ltr').addClass('rtl') : $('body').removeClass('rtl').addClass('ltr')}
  let fontFamily = 'cairo';
{locale === 'en' ? fontFamily='lato': ''}
  return (
    <html lang={locale}>
      <body /*className={inter.className}*/ style={{fontFamily: `${fontFamily}`}}>
        <div className="container">
          <NextIntlClientProvider messages={messages}>
            {children}
            {/* <div style={{background: 'black', height: '100vh'}}></div> */}
          </NextIntlClientProvider>
          {/* <Background /> */}
        </div>
      </body>
    </html>
  );
}
