name: academia
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  provider: ^6.0.5
  fluttertoast: ^8.2.2
  bloc_provider: ^1.0.0
  lottie: ^3.0.0
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.1
  expandable_text: ^2.3.0
  shimmer: ^3.0.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  dio: ^5.3.3
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.6.7
  retrofit_generator: ^8.1.0
  logger: ^2.0.2+1
  dartz: ^0.10.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  circle_nav_bar: ^2.0.1+1
  table_calendar: ^3.1.0
  floating_bottom_bar: ^0.0.3
  curved_navigation_bar: ^1.0.3
  animated_bottom_navigation_bar: ^1.3.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:


  uses-material-design: true
  assets:
     - assets/images/

  fonts:
      - family: Quicksand
        fonts:
          - asset: assets/fonts/Quicksand-Bold.ttf
            weight: 700
          - asset: assets/fonts/Quicksand-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Quicksand-Medium.ttf
            weight: 500
          - asset: assets/fonts/Quicksand-Regular.ttf
            weight: 400
          - asset: assets/fonts/Quicksand-Light.ttf
            weight: 300
      - family: Cairo
        fonts:
          - asset: assets/fonts/Cairo-Bold.ttf
            weight: 700
          - asset: assets/fonts/Cairo-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Cairo-Medium.ttf
            weight: 500
          - asset: assets/fonts/Cairo-Regular.ttf
            weight: 400
          - asset: assets/fonts/Cairo-Light.ttf
            weight: 300

flutter_assets:
  assets_path: assets/images/
  output_path: lib/presentation/resources/
  filename: assets_manager.dart
  field_prefix: 



