import { Inter, Cairo } from "next/font/google";
import "./globals.css";
import Background from "../components/Background/Background";
import { ThemeProvider } from "@/context/ThemeContext";
import DarkModeToggle from "../components/DarkModeToggle/DarkModeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider> */}
        <div className="container">
          {/* <DarkModeToggle /> */}
          {children}
        </div>
        {/* </ThemeProvider> */}
        <Background />
      </body>
    </html>
  );
}
